# Advanced Tensors

### Indexing Tensors

- Tensors can be indexed just like Python lists

In [1]:
import tensorflow as tf


rank_4_tensor = tf.zeros([2, 3, 4, 6])
# Get the first 2 elements of each dimension
result = rank_4_tensor[:2, :2, :2, :2]
result

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [2]:
# Get first element from each dimension from each index except for the final one
result = rank_4_tensor[:1, :1, :1, :]
result

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_2_tensor = tf.constant([[10, 5],
                             [2, 6]])

### Extending tensors

In [4]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [5]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 5]],

       [[ 2],
        [ 6]]], dtype=int32)>

In [6]:
new_rank_3_tensor = rank_2_tensor[tf.newaxis, ...]

In [7]:
new_rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  5],
        [ 2,  6]]], dtype=int32)>

In [8]:
new_tensor = tf.expand_dims(rank_4_tensor, axis=2)

In [9]:
new_tensor

<tf.Tensor: shape=(2, 3, 1, 4, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

# Manipulating Tensors(Tensor operations)

**Basic operations**<br>
`+`, `-`, `*`, `/`

In [10]:
tensor = tf.constant([[24, 12], [11, 3]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[34, 22],
       [21, 13]], dtype=int32)>

In [11]:
# all other operations work tensorwise
# We can use tensorflow builtin functions

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[240, 120],
       [110,  30]], dtype=int32)>

In [12]:
tf.add(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 15],
       [14,  6]], dtype=int32)>

### Matrix Multiplication

In [13]:
print(tensor)

tf.Tensor(
[[24 12]
 [11  3]], shape=(2, 2), dtype=int32)


In [14]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[708, 324],
       [297, 141]], dtype=int32)>

In [15]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[576, 144],
       [121,   9]], dtype=int32)>

In [16]:
tensor**tensor # outputs weird numbers, because it's 32bit integers

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[         0, -251658240],
       [1843829075,         27]], dtype=int32)>

In [17]:
tensor@tensor # matrix multiplication using python

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[708, 324],
       [297, 141]], dtype=int32)>

### Dot product

 Different kinds of matrix multiplication
* `tf.matmul()`
* `tf.tensordot()`



In [18]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9, 10], [11, 12]])

In [19]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [20]:
# Perform matrix multiplication b-ween X and Y (reshaped)

tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [21]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

### Changing the datatype of a Tensor

In [22]:
B = tf.constant([.6, 1.3])
B.dtype

tf.float32

### Tensor aggregation

In [23]:
D = tf.constant([-4, -6])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-4, -6], dtype=int32)>

In [24]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [25]:
import numpy as np

E = tf.constant(np.random.randint(0, 100, size=50))
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [26]:
# Find the minimum
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([43, 64, 40, 54, 65, 73, 82, 60, 64, 96, 82, 46, 45, 48, 87, 25,  5,
       69, 60, 66,  8, 95, 60,  9,  6, 90, 57, 65, 97,  7, 67, 76, 65, 21,
        5, 21, 91, 14, 97, 75, 22,  6, 20, 17, 21, 80,  4, 88,  2, 57])>

In [27]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [28]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [29]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [30]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2517>

In [31]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.613468>

In [32]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=937>

In [33]:
837**.5

28.930952282978865