# Tensorflow first steps

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & <a href="https://numpy.org/">NumPy</a>
* Using <a href="https://www.tensorflow.org/api_docs/python/tf/function">@tf.function</a> (a way to speed up your regular Python functions)
* Using GPUs(or TPUs) with TensorFlow

## Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__) # tensorflow version

2.8.2


### Create tensors with <a href="https://www.tensorflow.org/api_docs/python/tf/constant">tf.constant()</a>

In [2]:
scalar = tf.constant(10)
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
# Check the number of dimensions(ndim) of a tensor

scalar.ndim

0

In [4]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix

matrix = tf.constant([[5, 9], [2, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 9],
       [2, 4]], dtype=int32)>

In [7]:
matrix.ndim

2

### Create tensors with <a href="https://www.tensorflow.org/api_docs/python/tf/Variable">tf.Variable()</a>

In [8]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [9]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([4, 8])
unchangeable_tensor = tf.constant([4, 8])

In [10]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>)

In [11]:
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>


In [12]:
# Let's try change one of the elements in our changeable tensor

# changeable_tensor[0] = 8 # 'ResourceVariable' object does not support item assignment
# changeable_tensor

In [13]:
# Right way
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 8], dtype=int32)>

In [14]:
# unchangeable_tensor[0] = 4 -> TypeError
# unchangeable_tensor.assign(8) -> AttributeError

### Creating random tensors

Random tensors are tensors of some definite size which contain random numbers

In [15]:
# Create two random but the same tensors

random_1 = tf.random.Generator.from_seed(35)
random_1 = random_1.normal(shape=(3, 7))
random_1

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 , -0.645002  ,
         0.18022095, -0.14656258],
       [ 0.34374258,  0.41367555,  0.17573498, -1.0871261 ,  0.45905176,
         0.20386009,  0.562024  ],
       [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
         1.5428121 ,  0.78953624]], dtype=float32)>

In [16]:
random_2 = tf.random.Generator.from_seed(35)
random_2 = random_2.normal(shape=(3, 7))
random_2

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 , -0.645002  ,
         0.18022095, -0.14656258],
       [ 0.34374258,  0.41367555,  0.17573498, -1.0871261 ,  0.45905176,
         0.20386009,  0.562024  ],
       [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
         1.5428121 ,  0.78953624]], dtype=float32)>

In [17]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
 array([[ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 , -0.645002  ,
          0.18022095, -0.14656258],
        [ 0.34374258,  0.41367555,  0.17573498, -1.0871261 ,  0.45905176,
          0.20386009,  0.562024  ],
        [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
          1.5428121 ,  0.78953624]], dtype=float32)>,
 <tf.Tensor: shape=(3, 7), dtype=float32, numpy=
 array([[ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 , -0.645002  ,
          0.18022095, -0.14656258],
        [ 0.34374258,  0.41367555,  0.17573498, -1.0871261 ,  0.45905176,
          0.20386009,  0.562024  ],
        [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
          1.5428121 ,  0.78953624]], dtype=float32)>,
 <tf.Tensor: shape=(3, 7), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True

In [18]:
tf.math.reduce_all(tf.equal(random_1, random_2))

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Shuffling the order of elements in tensors

In [19]:
not_shuffled = tf.constant([[1, 4], [2, 3], [6, 9]])
not_shuffled.ndim

2

In [20]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 9],
       [1, 4],
       [2, 3]], dtype=int32)>

### 🛠 Create five random tensors and shuffle all of them

In [21]:
first = tf.random.Generator.from_seed(45).uniform(shape=(4, 5))
print(f'First tensor before shuffling : \n{first}')
first_shuffled = tf.random.shuffle(first)
print(f'First tensor after shuffling : \n{first_shuffled}')

First tensor before shuffling : 
[[0.86540747 0.8862978  0.27795732 0.8857763  0.2179842 ]
 [0.29115117 0.03953862 0.8136791  0.8139852  0.52180684]
 [0.12496924 0.5488483  0.7755773  0.6184403  0.24936223]
 [0.89341843 0.28422844 0.70332646 0.2622137  0.4432162 ]]
First tensor after shuffling : 
[[0.12496924 0.5488483  0.7755773  0.6184403  0.24936223]
 [0.89341843 0.28422844 0.70332646 0.2622137  0.4432162 ]
 [0.29115117 0.03953862 0.8136791  0.8139852  0.52180684]
 [0.86540747 0.8862978  0.27795732 0.8857763  0.2179842 ]]


In [22]:
second = tf.random.Generator.from_seed(50).normal(shape=(3, 7))
print(f'Second tensor before shuffling : \n{second}')
second_shuffled = tf.random.shuffle(second)
print(f'Second tensor after shuffling : \n{second_shuffled}')

Second tensor before shuffling : 
[[ 0.45331386  1.1487608  -1.2659091  -0.47450137  2.006022    0.28288034
  -0.30288252]
 [-1.443651    1.0034493   0.20857747  0.35700995  1.0648885   1.2432485
  -2.2173238 ]
 [ 0.18706243  0.6617961   0.01380118 -0.24827152  1.2111493  -0.7199124
  -0.04082382]]
Second tensor after shuffling : 
[[ 0.45331386  1.1487608  -1.2659091  -0.47450137  2.006022    0.28288034
  -0.30288252]
 [ 0.18706243  0.6617961   0.01380118 -0.24827152  1.2111493  -0.7199124
  -0.04082382]
 [-1.443651    1.0034493   0.20857747  0.35700995  1.0648885   1.2432485
  -2.2173238 ]]


In [23]:
third = tf.random.Generator.from_seed(16).normal(shape=(4, 2))
print(f'Third tensor before shuffling : \n{third}')
third_shuffled = tf.random.shuffle(third)
print(f'Third tensor after shuffling : \n{third_shuffled}')

Third tensor before shuffling : 
[[-0.63509274  0.3703566 ]
 [-1.0939722  -0.4601445 ]
 [ 1.5420506  -0.16822556]
 [-0.4390865  -0.4129243 ]]
Third tensor after shuffling : 
[[-0.63509274  0.3703566 ]
 [-0.4390865  -0.4129243 ]
 [-1.0939722  -0.4601445 ]
 [ 1.5420506  -0.16822556]]


In [24]:
forth = tf.random.Generator.from_seed(10).normal(shape=(3, 9))
print(f'Forth tensor before shuffling : \n{forth}')
forth_shuffled = tf.random.shuffle(forth)
print(f'Forth tensor after shuffling : \n{forth_shuffled}')

Forth tensor before shuffling : 
[[-0.29604465 -0.21134205  0.01063002  1.5165398   0.27305737 -0.29925638
  -0.3652325   0.61883307 -1.0130816 ]
 [ 0.28291714  1.2132233   0.46988967  0.37944323 -0.6664026   0.6054596
   0.19181173  0.8045827   0.4769051 ]
 [-0.7812124  -0.996891    0.33149973 -0.5445254   1.5222508   0.59303206
  -0.63509274  0.3703566  -1.0939722 ]]
Forth tensor after shuffling : 
[[-0.29604465 -0.21134205  0.01063002  1.5165398   0.27305737 -0.29925638
  -0.3652325   0.61883307 -1.0130816 ]
 [-0.7812124  -0.996891    0.33149973 -0.5445254   1.5222508   0.59303206
  -0.63509274  0.3703566  -1.0939722 ]
 [ 0.28291714  1.2132233   0.46988967  0.37944323 -0.6664026   0.6054596
   0.19181173  0.8045827   0.4769051 ]]


In [25]:
fifth = tf.random.Generator.from_seed(78).normal(shape=(11, 4))
print(f'Fifth tensor before shuffling : \n{fifth}')
fifth_shuffled = tf.random.shuffle(fifth)
print(f'Fifth tensor after shuffling : \n{fifth_shuffled}')

Fifth tensor before shuffling : 
[[-1.4084325  -1.8613014   1.0928144  -0.29996362]
 [-0.7382552   1.2053189  -0.3511434   0.13897082]
 [ 0.32744762 -0.3579723   1.230323   -0.13087   ]
 [-0.44519424  0.9551449   0.24270573 -0.02293015]
 [-0.97063404 -0.7102746   0.4939478   2.1883757 ]
 [-0.4953925  -0.7584407   0.13736533 -0.44198883]
 [-0.65641224 -2.286797    0.07126775  2.3546813 ]
 [ 2.2539537  -0.8510308   0.8119971   2.0856276 ]
 [ 0.45117483 -0.90232193 -1.5350152   0.18753827]
 [ 0.01724745  1.071573    0.32903498 -0.12147247]
 [-0.81168556  1.0684562   0.03192343  0.37305453]]
Fifth tensor after shuffling : 
[[ 0.01724745  1.071573    0.32903498 -0.12147247]
 [ 0.32744762 -0.3579723   1.230323   -0.13087   ]
 [ 0.45117483 -0.90232193 -1.5350152   0.18753827]
 [-0.44519424  0.9551449   0.24270573 -0.02293015]
 [-0.97063404 -0.7102746   0.4939478   2.1883757 ]
 [-0.4953925  -0.7584407   0.13736533 -0.44198883]
 [-1.4084325  -1.8613014   1.0928144  -0.29996362]
 [-0.81168556  1

### Creating tensors from NumPy arrays

In [26]:
import numpy as np
array = np.array([[1,2,3],[3,4,5],[5,6,7]])
tensor = tf.convert_to_tensor(array)
print(f'NumPy array : \n{array}')
print(f'Tensor : \n{tensor}')

NumPy array : 
[[1 2 3]
 [3 4 5]
 [5 6 7]]
Tensor : 
[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [27]:
tensor

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])>

### Other ways to make tensor

In [28]:
tf.ones([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [29]:
tf.ones((1, 5))

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [31]:
tf.zeros((4, 6))

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Getting more information from your tensors (tensor attributes)

<style>
	.demo {
		width:100%;
		height:100%;
		border:1px solid #C0C0C0;
		border-collapse:collapse;
		padding:5px;
	}
	.demo th {
		border:1px solid #C0C0C0;
		padding:5px;
		background:#F0F0F0;
	}
	.demo td {
		border:1px solid #C0C0C0;
		padding:5px;
	}
</style>
<table class="demo">
	<caption><br></caption>
	<thead>
	<tr>
		<th>Attribute</th>
		<th>Meaning</th>
		<th>Code</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>&nbsp;Shape</td>
		<td>&nbsp;The length of each of the elements of the tensor</td>
		<td>&nbsp;tensor.shape</td>
	</tr>
	<tr>
		<td>&nbsp;Rank</td>
		<td>&nbsp;The number of tensor dimensions.</td>
		<td>&nbsp;tensor.ndim</td>
	</tr>
	<tr>
		<td>&nbsp;Axis or Dimension</td>
		<td>&nbsp;A particular dimension of a tensor.</td>
		<td>&nbsp;tensor[0], tensor[:,&nbsp; 1]</td>
	</tr>
	<tr>
		<td>&nbsp;Size</td>
		<td>&nbsp;The total number of items in the tensor</td>
		<td>&nbsp;tf.size(tensor)</td>
	</tr>
	</tbody>
</table>

In [32]:
zeros = tf.zeros([2, 4, 3, 5])
zeros

<tf.Tensor: shape=(2, 4, 3, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
zeros.shape

TensorShape([2, 4, 3, 5])

In [34]:
zeros.ndim

4

In [35]:
tf.size(zeros)

<tf.Tensor: shape=(), dtype=int32, numpy=120>